// src/lib/Header.svelte
<script>
  import { resolve } from "$app/paths"
  import { session } from "$lib/auth.svelte"
</script>

<header>
  <h1><a href={resolve("/")}>WorshipMate</a></h1>
  <nav>
    <ul>
      <li><a href={resolve("/about")}>About</a></li>
      {#if session !== null}
        <li><a href={resolve("/dashboard")}>Dashboard</a></li>
      {/if}
      {#if session === null}
        <li><a href={resolve("/login")}>Login</a></li>
      {/if}
    </ul>
  </nav>
</header>

<style>
  header {
    display: grid;
    grid-template-columns: min-content auto;
    justify-content: space-between;
    gap: 1rem;
    padding: 1.5rem;
    background: var(--primary);
    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.75);

    color: var(--white);
    a {
      color: inherit;
    }
  }

  h1 {
    --shadow: 2px 2px 2px rgba(0, 0, 0, 0.9);

    display: inline-block;

    font-family: var(--font-alegreya-sc);
    font-size: 3rem;
    text-shadow: var(--shadow);

    a {
      padding: 0.25rem 0.5rem;
      border: 3px solid var(--white);
      box-shadow: var(--shadow);

      &:hover {
        color: var(--white);
      }
    }
  }

  nav ul {
    display: grid;
    grid-auto-flow: column;
    gap: 2rem;

    font-family: var(--font-alegreya-sc);
    text-transform: lowercase;
    font-size: 1.5rem;
    a {
      font-weight: 400;
    }
  }
</style>

// client/lib/layout/Header.tsx
import styled from 'styled-components'

import { color, font, fontFamily } from '~/theme'

export type HeaderProps = {
  isUserLoggedIn?: boolean
}

export function Header({ isUserLoggedIn }: HeaderProps) {
  return (
    <HeaderContainer>
      <div>
        <Title href="/">WorshipMate</Title>
      </div>
      <Links>
        <Link href="#">About</Link>
        {isUserLoggedIn ? (
          <Link href="#">Dashboard</Link>
        ) : (
          <Link href="/login">Login</Link>
        )}
      </Links>
    </HeaderContainer>
  )
}

const HeaderContainer = styled.div`
  display: grid;
  grid-template-columns: auto max-content;
  grid-gap: 20px;
  padding: 20px;
  background: ${color('primary')};
  box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.75);
`

const shadow = '2px 2px 2px rgba(0, 0, 0, 0.9)'

const Title = styled.a`
  display: inline-block;
  margin: 0;
  padding: 5px 10px;
  color: ${color('white')};
  font-family: ${fontFamily('alegreyaSC')};
  font-size: 2.5rem;
  border-color: ${color('white')};
  border-width: 3px;
  border-style: solid;
  text-shadow: ${shadow};
  box-shadow: ${shadow};
  letter-spacing: 1px;

  &:hover {
    color: ${color('white')};
  }
`

const Links = styled.nav`
  display: grid;
  justify-items: end;
  align-items: center;
`

const Link = styled.a`
  ${font('label')}
  font-size: 1.2rem;
  color: ${color('white')};
`
